name: rythm
description: ""
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^3.2.1

  # Database
  drift: ^2.22.1
  drift_flutter: ^0.2.7
  sqlite3_flutter_libs: ^0.5.41

  # Routing
  go_router: ^17.1.0

  # Utils
  path_provider: ^2.1.5
  path: ^1.9.1
  intl: ^0.20.2
  share_plus: ^12.0.1
  file_picker: ^10.3.10
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.22.1
  build_runner: ^2.4.13
  mocktail: ^1.0.4
  sqlite3: ^2.7.3
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
